//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MelbourneMH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmissionsVIC
    {
        public int Year { get; set; }
        public double Electricity_Generation { get; set; }
        public double Direct_Combustion { get; set; }
        public double Transport { get; set; }
        public double Fugitive_emissions { get; set; }
        public double Industrial_Processes { get; set; }
        public double Agriculture { get; set; }
        public double LULUCF { get; set; }
        public double Waste { get; set; }
        public double Total__net_emissions_ { get; set; }
    }
}
