//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MelbourneMH.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MBMHI2 : DbContext
    {
        public MBMHI2()
            : base("name=MBMHI2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ancestry> Ancestry { get; set; }
        public virtual DbSet<Birthplace> Birthplace { get; set; }
        public virtual DbSet<Language> Language { get; set; }
        public virtual DbSet<Population_Melbourne_Trendline> Population_Melbourne_Trendline { get; set; }
        public virtual DbSet<Population_Suburb> Population_Suburb { get; set; }
        public virtual DbSet<Religion> Religion { get; set; }
        public virtual DbSet<Sex_Ratio_Suburbs> Sex_Ratio_Suburbs { get; set; }
        public virtual DbSet<EmissionsVIC> EmissionsVIC { get; set; }
        public virtual DbSet<Rainfall> Rainfall { get; set; }
        public virtual DbSet<Temperature> Temperature { get; set; }
        public virtual DbSet<Trees> Trees { get; set; }
    }
}
